// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Database;

#nullable disable

namespace Web.Migrations
{
    [DbContext(typeof(IASBContext))]
    [Migration("20251106013046_SeedPerguntasIniciais2")]
    partial class SeedPerguntasIniciais2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Web.Database.Model.Pergunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Perguntas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ordem = 1,
                            Texto = "NÚMERO DE ALUNOS PRESENTES:"
                        },
                        new
                        {
                            Id = 2,
                            Ordem = 2,
                            Texto = "QUANTOS ESTUDARAM DIARIAMENTE A BÍBLIA E A LIÇÃO?"
                        },
                        new
                        {
                            Id = 3,
                            Ordem = 3,
                            Texto = "QUANTOS PARTICIPARAM DE UM PEQUENO GRUPO NESTA SEMANA?"
                        },
                        new
                        {
                            Id = 4,
                            Ordem = 4,
                            Texto = "QUANTOS DERAM ALGUM ESTUDO BÍBLICO NESTA SEMANA?"
                        },
                        new
                        {
                            Id = 5,
                            Ordem = 5,
                            Texto = "QUANTOS REALIZARAM ALGUMA OUTRA ATIVIDADE MISSIONÁRIA UTILIZANDO SEU TALENTO?"
                        });
                });

            modelBuilder.Entity("Web.Database.Model.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("Web.Database.Model.Sabado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlunosPresentes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstudoDiarioBibliaLicao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstudosBiblicosDados")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutrasAtividadesMissionarias")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipacaoPequenoGrupo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Trimestre")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Sabados");
                });

            modelBuilder.Entity("Web.Database.Model.SabadoAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PessoaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SabadoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.HasIndex("SabadoId");

                    b.ToTable("SabadoAlunos");
                });

            modelBuilder.Entity("Web.Database.Model.SabadoAluno", b =>
                {
                    b.HasOne("Web.Database.Model.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Database.Model.Sabado", "Sabado")
                        .WithMany()
                        .HasForeignKey("SabadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");

                    b.Navigation("Sabado");
                });
#pragma warning restore 612, 618
        }
    }
}
